### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by ghost** [Techcraft7/7Sharp#32]
Hi.where can find more examples of 7Sharp ?

**Comment by Techcraft7** [comment]
I am currently working in docs. Check out the wiki for some samples. If you download the latest beta for 2.0 (see read me), I added a manual that documents most built in functions and other things. It’s a work in progress right now.
In the wiki, the version 1.8 page should be the most help right now.

**Comment by Techcraft7** [comment]
I’m not at my computer right now but I will add a quick getting started page.

**Comment by ghost** [comment]
if else statement document in Get Started Page have a wrong markdown.
[this is here](https://github.com/Techcraft7/7Sharp/wiki/Getting-Started#if-statements)

**Comment by Techcraft7** [comment]
I know I was typing on my phone

**Comment by Techcraft7** [comment]
i have added a lot of stuff to the docs. Hope it helps!
