### ISSUE TITLE
Can use C# libraries?

### ISSUE THREAD

**Issue by ghost** [Techcraft7/7Sharp#37]
Hi. How can I use C # libraries in 7sharp? Is there such a feature?
for example :
```
import "System.Data";
```
I have a suggestion. It is better to run 7sharp code through a terminal command.
example :
```
7sharp run script.7s
```
It's easier.

**Comment by Techcraft7** [comment]
currently not yet. Could possibly be implemented. When desigining 7Sharp I was trying to avoid access to C#'s built in functions for security and simplicity.

If you want you can fork the project, and add a custom system library. See `LibIO.cs` and `LibRandom.cs` for examples.
Make sure to update `SysLibraries.GetAllLibraries()`

**Comment by Techcraft7** [comment]
Also make sure to add plenty of user friendly error messages.

throw an `InterpreterException` to make the errors simpler.
Check `SysFunctions.cs` for some examples

**Comment by Techcraft7** [comment]
@hasan-kashi if you want to run a script through the terminal, do `7Sharp script.7s`
